Switch to kiwi-ng
openSUSE/docker-containers pull request #70
Opened 2017-08-01 10:25 UTC by davidcassany

This PR updates the KIWI projects for opensuse base images (42.2, 42.3, Tumbleweed) in order to make use the current KIWI-NG which is capable to make native docker images.

This PR is related to an update of the opensuse publication pipe in Jenkins, see [here](https://gitlab.suse.de/docker/docker-publisher/merge_requests/4)

2017-08-03 07:46 UTC, flavio requested changes
Everything looks really good. There are just some minor things to change.

2017-08-03 07:46 UTC, flavio commented on openSUSE-Leap-42.1/config.kiwi
>      <contact>fcastelli@suse.com</contact>
Given we now have a team, I propose to switch my personal details with the one of the team. Use the same data we use for the SLE images

2017-08-03 07:46 UTC, flavio commented on openSUSE-Leap-42.2/config.kiwi
>      <contact>fcastelli@suse.com</contact>
Same here

2017-08-03 07:46 UTC, flavio commented on openSUSE-Leap-42.3/config.kiwi
>      <contact>fcastelli@suse.com</contact>
Same here

2017-08-03 07:46 UTC, flavio commented on openSUSE-Tumbleweed/config.kiwi
>      <contact>fcastelli@suse.com</contact>
Same here

2017-08-03 10:04 UTC, davidcassany commented on openSUSE-Leap-42.1/config.kiwi
>      <contact>fcastelli@suse.com</contact>
The SLE images they have the same issue, <author> and <contact> make reference to Thomas Boerger. Shall we use then the "SUSE Containers Team" as author and "containers@suse.com" as the contact, like in the maintainer label of the docker metadata? Or maybe we should some sort of more official name, like "SUSE Kubernetes Core Team"?

2017-08-03 10:06 UTC, flavio commented on openSUSE-Leap-42.1/config.kiwi
>      <contact>fcastelli@suse.com</contact>
I think "SUSE Containers Team" as author and "containers@suse.com" as contact are fine.

Can you fix the SLE images too please?

2017-08-04 12:29 UTC, davidcassany commented on openSUSE-Leap-42.1/config.kiwi
>      <contact>fcastelli@suse.com</contact>
Right I will update them too

2017-08-04 16:10 UTC, davidcassany commented on openSUSE-Leap-42.1/config.kiwi
>      <contact>fcastelli@suse.com</contact>
I haven't updated Leap 42.1 author and contact since it is not supported anymore and IMHO it should be deleted from this repository, as it was 13.2.

2017-08-08 07:38 UTC, flavio approved these changes

2017-08-08 07:38 UTC, flavio commented
LGTM, let's drop the unsupported distributions with a separate PR

2017-08-08 07:39 UTC, flavio commented
@davidcassany please merge the PR once you are back from vacation

2017-09-04 15:29 UTC, merged